### ISSUE TITLE
A few questions about your idea

### ISSUE THREAD

**Issue by YSL0226** [bryandlee/FreezeG#10]
Thank you for your great work.
After I read description in ReamMe and codes, I got confuse. 

updae:  Sorry, I get mistake in the pervious post. The 32 in `convs.15` 's weight ([1, 32, 32, 3, 3]) is channel.
So you train large feature map resolution of generator, right?

==========
Did you freeze generator layers in 16*16, 32*32 resolution, etc.?
At first I thought you freeze large feature map resolution weights. However, from the code `requires_grad(generator, True, target_layer=f'convs.{generator.num_layers-2-2*loc}')`, your turn on grade in `convs.15`.
`convs.15` 's weight is [1, 32, 32, 3, 3]. It means you train low feature map resolution weight in generator?
(You didn't train in large feature map resolution, such as, 256, 512).
Is it correct?

**Comment by bryandlee** [comment]
Hi, that's correct. The weights for large feature maps are trained.
