### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by HideUnderBush** [bryandlee/FreezeG#3]
Thanks a lot for your work, it is fantastic!

Could you please share the pre-trained models?

Many Thanks!!!

**Comment by bryandlee** [comment]
Hi, I added a test script with some pre-trained models:

cat: [link](https://drive.google.com/file/d/1cQdrClDwZ6I8DIZvRWjwo9y9_o7TK5RC/view?usp=sharing)

cat2wild: [link](https://drive.google.com/file/d/11o8vUe3MYQPxGN1A3YdV9uUg7e3QJs1x/view?usp=sharing)

FFHQ model from [rosinality](https://github.com/rosinality/stylegan2-pytorch): [link](https://drive.google.com/open?id=1PQutd-JboOCOZqmd95XWxWrO8gGEvRcO)

ffhq2met: [link](https://drive.google.com/file/d/1aBo8DjCaCQV5dSHU_NhHiRH7y1FxkZc2/view?usp=sharing)

ffhq2dog: [link](https://drive.google.com/file/d/1ABsZgTNSb-CzfHtLnAy9xEQfDld3-VJd/view?usp=sharing)

Gradio module is needed for the interactive demo (gradio_app.py).

**Comment by johndpope** [comment]
https://github.com/johndpope/maskbackend/blob/master/pretrained_networks.py


Is the pt file same as pkl? Seems stylegan2 provide standard format for saved network.

Is the simpsons available?

**Comment by bryandlee** [comment]
As far as I know, both formats use the same serialization scheme but pt has additional pytorch tensor-related functionality. I guess the model files provided by NVLabs are for tensorflow and you need to convert the weights as described [here](https://github.com/rosinality/stylegan2-pytorch#convert-weight-from-official-checkpoints).

For the datasets, check out [this Issue](https://github.com/bryandlee/FreezeG/issues/2).
