### ISSUE TITLE
Can't generate images from pretrained model

### ISSUE THREAD

**Issue by abelghazinyan** [bryandlee/FreezeG#6]
I am trying to run `generate.py` on your pretrained model 55000.pt and on my finetuned model which is done on your pretrained ffhq model. But I am getting an error.

command: `python generate.py --ckpt 550000.pt --size 256`

error:
 `Traceback (most recent call last):
  File "generate.py", line 47, in <module>
    g_ema.load_state_dict(checkpoint['g_ema'])
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Generator:
        Missing key(s) in state_dict: "noises.noise_0", "noises.noise_1", "noises.noise_2", "noises.noise_3", "noises.noise_4", "noises.noise_5", "noises.noise_6", "noises.noi
se_7", "noises.noise_8", "noises.noise_9", "noises.noise_10", "noises.noise_11", "noises.noise_12". `

**Comment by bryandlee** [comment]
Setting strict=False at load_state_dict would work.
