### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by icoric4** [bryandlee/FreezeG#7]
Hello and great work! 

I have a few questions regarding a gif you posted https://github.com/bryandlee/FreezeG/blob/master/imgs/face2art/2.gif and I hope you can help me with it. 

I would like to do the same transfer of real face to art on my own images. Am I right to assume that you are using 2 stylegan2 models trained on FFHQ and Metfaces. Then you generated latent vectors using ffhq model and then generate the art image using this latent vectors and the model trained on Metfaces?

Also, at the end of the gif there is a constant image (of a boy) and the style changes. May I know which eigenvector (vectors) are you using for this?

Thanks!

**Comment by bryandlee** [comment]
Hi, 

That's correct, and the eigenvectors are from the closed-form factorization method(SeFa).

**Comment by icoric4** [comment]
Thanks! Great. 

Do you maybe remember which eigenvectors (which id from 0-511) did you use for generating images below?

<img width="1440" alt="Screen Shot 2021-01-25 at 16 17 31" src="https://user-images.githubusercontent.com/16475640/107278321-e57ef800-6a55-11eb-9841-cd5deafbcf3e.png">
<img width="1440" alt="Screen Shot 2021-01-25 at 16 17 30" src="https://user-images.githubusercontent.com/16475640/107278325-e6b02500-6a55-11eb-9e40-2c326e4d250b.png">
<img width="1440" alt="Screen Shot 2021-01-25 at 16 17 29" src="https://user-images.githubusercontent.com/16475640/107278326-e748bb80-6a55-11eb-98da-9db658577b14.png">
<img width="1440" alt="Screen Shot 2021-01-25 at 16 17 32" src="https://user-images.githubusercontent.com/16475640/107278311-e021ad80-6a55-11eb-9ce4-71dcfbd542cc.png">

**Comment by bryandlee** [comment]
The directions are randomly chosen from the first 20 eigenvectors for the gifs. I don't remember the exact vectors for each frame tho. Hope it helps!
